package com.example.demo.model;

public enum Provincia {
    ALAVA, ALBACETE, ALICANTE, ALMERIA, ASTURIAS, AVILA, BADAJOZ, BALEARES,
    BARCELONA, BURGOS, CACERES, CADIZ, CANTABRIA, CASTELLON, CEUTA, CIUDAD_REAL,
    CORDOBA, CUENCA, GIRONA, GRANADA, GUADALAJARA, GUIPUZCOA, HUELVA, HUESCA,
    JAEN, LA_CORUNA, LA_RIOJA, LAS_PALMAS, LEON, LLEIDA, LUGO, MADRID, MALAGA,
    MELILLA, MURCIA, NAVARRA, OURENSE, PALENCIA, PONTEVEDRA, SALAMANCA,
    SANTA_CRUZ_DE_TENERIFE, SEGOVIA, SEVILLA, SORIA, TARRAGONA, TERUEL,
    TOLEDO, VALENCIA, VALLADOLID, VIZCAYA, ZAMORA, ZARAGOZA
}