hackaton.api.jwt=${API_TOKEN:token_de_desarrollo_por_defecto}
hackaton.api.base-url=http://ec2-54-171-51-31.eu-west-1.compute.amazonaws.com
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esto permite que la base de datos no se borre cada vez que cambias código si usas archivos
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=